--------------------------------------------------------
--  파일이 생성됨 - 수요일-5월-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."NOTICE" 
   (	"NO" NUMBER(*,0), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"RESDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"VISITED" NUMBER(*,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."QNA" 
   (	"NO" NUMBER(*,0), 
	"PLEVEL" NUMBER(*,0), 
	"PARNO" NUMBER(*,0), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"RESDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"VISITED" NUMBER(*,0) DEFAULT 0, 
	"AID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DATA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DATA" 
   (	"NO" NUMBER(*,0), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"DATAFILE" VARCHAR2(200 BYTE), 
	"RESDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"VISITED" NUMBER(*,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GUIDE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GUIDE" 
   (	"PCODE" NUMBER(*,0), 
	"PNAME" VARCHAR2(100 BYTE), 
	"PTYPE" VARCHAR2(3 BYTE), 
	"PADDR" VARCHAR2(200 BYTE), 
	"PTEL" VARCHAR2(20 BYTE), 
	"PGPS" VARCHAR2(50 BYTE), 
	"PCOMENT" VARCHAR2(2000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.NOTICE
SET DEFINE OFF;
Insert into SYSTEM.NOTICE (NO,TITLE,CONTENT,RESDATE,VISITED) values (1,'더미 제목1-수정','더미 내용1-수정',to_timestamp('24/04/04 11:29:27.000000000','RR/MM/DD HH24:MI:SSXFF'),3);
Insert into SYSTEM.NOTICE (NO,TITLE,CONTENT,RESDATE,VISITED) values (3,'더미 글 제목3','더미 글 내용3 입니다.',to_timestamp('24/04/04 14:30:29.000000000','RR/MM/DD HH24:MI:SSXFF'),2);
REM INSERTING into SYSTEM.QNA
SET DEFINE OFF;
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (1,1,1,'질문1','질문1내용',to_timestamp('24/04/12 11:16:41.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'kkt');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (2,2,1,'질문1의 답변1','질문1의 답변 내용',to_timestamp('24/04/12 11:25:18.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'admin');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (3,1,3,'질문2','질문2의 내용',to_timestamp('24/04/12 11:27:49.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'kkt');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (4,1,4,'질문3','질문3 내용',to_timestamp('24/04/12 11:29:27.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'kkt');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (5,1,5,'질문4','질문4의 내용임',to_timestamp('24/04/12 11:29:49.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'kkt');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (6,2,3,'질문2의 답변1','질문2의 답변 내용',to_timestamp('24/04/12 11:30:56.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'admin');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (7,2,4,'질문3의 답변1','질문3의 답변 내용',to_timestamp('24/04/12 11:31:21.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'admin');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (8,1,8,'질문5','질문5의 내용임',to_timestamp('24/04/12 11:31:52.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'kkt');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (9,2,8,'질문5의 답변1','질문5의 답변 내용',to_timestamp('24/04/12 11:32:23.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'admin');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (10,2,5,'질문4의 답변1','질문4의 답변 내용',to_timestamp('24/04/12 11:32:48.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'admin');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (11,1,11,'질문6','배가 부르면 왜 졸리지?',to_timestamp('24/04/12 14:25:30.000000000','RR/MM/DD HH24:MI:SSXFF'),5,null);
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (12,1,12,'질문7','그래도 졸리면?',to_timestamp('24/04/12 14:28:55.000000000','RR/MM/DD HH24:MI:SSXFF'),4,'kkt');
Insert into SYSTEM.QNA (NO,PLEVEL,PARNO,TITLE,CONTENT,RESDATE,VISITED,AID) values (13,2,11,'질문6에 대한 답변 수정','식사 후에 졸린 이유는 섭취한 음식이 위에 오게 되면, 우리 몸의 이완을 담당하는 부교감 신경계가 활성화 되어 우리 몸이 휴식을 원하는 상태가 되기 때문입니다.
그래도 졸면 안돼지~!',to_timestamp('24/04/12 15:09:31.000000000','RR/MM/DD HH24:MI:SSXFF'),5,'admin');
REM INSERTING into SYSTEM.DATA
SET DEFINE OFF;
REM INSERTING into SYSTEM.GUIDE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008366
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008366" ON "SYSTEM"."NOTICE" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008373
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008373" ON "SYSTEM"."QNA" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008367
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008367" ON "SYSTEM"."DATA" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008365
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008365" ON "SYSTEM"."GUIDE" ("PCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NOTICE" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."QNA" MODIFY ("PLEVEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."QNA" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DATA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DATA" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUIDE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GUIDE" MODIFY ("PNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GUIDE" MODIFY ("PTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GUIDE" MODIFY ("PADDR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GUIDE" ADD PRIMARY KEY ("PCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."QNA" ADD FOREIGN KEY ("AID")
	  REFERENCES "SYSTEM"."MEMBER" ("ID") ENABLE;
