--------------------------------------------------------
--  파일이 생성됨 - 수요일-5월-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(300 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"ADDR" VARCHAR2(300 BYTE), 
	"POSTCODE" VARCHAR2(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MEMBER
SET DEFINE OFF;
Insert into SYSTEM.MEMBER (ID,PW,NAME,EMAIL,TEL,ADDR,POSTCODE) values ('admin','12345','관리자','admin@gasan.org','010-1234-5678','가산동 $ 287','12-345');
Insert into SYSTEM.MEMBER (ID,PW,NAME,EMAIL,TEL,ADDR,POSTCODE) values ('jdj','ac89','정도준','jdjac@naver.com','010-7979-1004','구로동 $ 381','45-678');
Insert into SYSTEM.MEMBER (ID,PW,NAME,EMAIL,TEL,ADDR,POSTCODE) values ('kkt','4321','김기태','kkt@gmail.com','02-1234-1234','을지로 47 $ 을지IT빌딩 204호','36-124');
--------------------------------------------------------
--  DDL for Index SYS_C008371
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008371" ON "SYSTEM"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
